name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Budowanie raz w tygodniu o północy w niedzielę
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Wersja Pythona, którą chcesz użyć

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: python project.py pathFile1.x pathFile2.y
        working-directory: path/to/project # Zmień na ścieżkę do twojego projektu

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: path/to/project/pathFile2.y # Zmień na ścieżkę do wygenerowanego pliku wykonywalnego w twoim projekcie

